<a href="https://colab.research.google.com/github/Amarjeet-1998/Amarjeet_Portfolio/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is NumPy?**

NumPy is a Python library used for working with arrays. it also has functions for working in domain of linear algebra, fourier transform, and the matrices. NumPy was created in 2005 by Travis Oliphant. It is an open sources project and you can use it freely. NumPy stands for Numerical Python.



# **Why Use NumPy?**

In python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.


# **Why is NumPy Faster than Lists?**


NumPy array are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behaviour is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. also it is optimized to work with latest CPU architectures.


# **Which Language is NumPy written in?** 

NumPy is a python library and is written partially in python, but most of the parts that require fast computation are written in C or C++.

In [1]:
'''To create an ndarray, we can pass a list, tuple or any array-like object into the array method, and it will be converted into an ndarray:'''

import numpy as np
arr = np.array([1,2,3,4,5]) #creating array
print(arr)
print(type(arr))     # check type of arr

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
print(np.__version__) # check numpy version

1.21.6


In [3]:
#use tuple to create numpy array
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
# create a 2-D array containing the values 1,2,3,4,5 and  6,7,8,9:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [5]:
#create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3,4,5
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#Numpy Array provides the ndim attribute that returns an integer that tells us how many dimemnsions
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
#create an array with  dimensions and verify that it has 5 dimensions:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [9]:
#access array element using indexing
arr = np.array([1,2,3,4])
print(arr[1])

print(arr[2] + arr[3])  #add two element in array using indexing

2
7


In [10]:
#accessing of 2D-array element
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:', arr[0,1])
print('5th element on 2nd row:', arr[1,4])

2nd element on 1st row: 2
5th element on 2nd row: 10


In [11]:
#Access 3-D arrays 
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2]) # Access the third element of the second array of the first array:

6


In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('last element from 2nd dim:', arr[1, -1])

last element from 2nd dim: 10


# **Slicing arrays**

slicing in python means taking elements from one given index to another given index.

we pass slice instead of index like this:[ start:end].

we can also define the step, like this :[start:end:step].

if we don't pass start its considered 0

if we don't pass end its considered length of array in that dimension

if we don't pass step its considered 1

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])
print(arr[2:4])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:3])
print(arr[::2])
print(arr[-1:3])
print(arr[::-2])
print(arr[2::])
print(arr[-2:3:1])
print(arr[3:])


[2 3 4 5]
[3 4]
[5 6 7]
[1 2 3 4]
[5 6]
[2 5]
[1 3 5 7]
[]
[7 5 3 1]
[3 4 5 6 7]
[]
[4 5 6 7]


In [14]:
#slicing 2-D arrays
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0, 0:6])
print(arr[0:2 , 2])
print(arr[0:2, 1:4])


[7 8 9]
[1 2 3 4 5]
[3 8]
[[2 3 4]
 [7 8 9]]


# **Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsign integers etc.

below is a list of all data types in NumPy and the characters used to represent them.

i-integer b-boolean u- unsigned integer f- float c-complex float m-timedelta M-datetime O- object S-string U-unicode string V- fixed chunk of memory for other type (void)

In [15]:
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

arr = np.array([1,2,3,4])
print(arr.dtype)

<U6
int64


In [16]:
#create a array with data type string
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [17]:
#create a array with data type string
arr = np.array([1,2,3,4], dtype ='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [18]:
#create an array with data type 4 bytes integer:
arr = np.array([1,2,3,4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


# **Converting Data Type on Existing Arrays**


The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype()function creates a copy of the array, and allows you to specify the data type as a parameter. 

the data type can be specified using a string, like 'f' for float, 'i'for integer etc. or you can use the data type directly like float for float and int for integer.

In [19]:
# change data type float into integer
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('int')
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int64


# **The Difference Between copy and view**

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own that data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [20]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# **Get the shape of an Array**

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [23]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


# **Reshaping arrays**

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [24]:
'''Convert the following 1-D array with elements into a 3-D array.
The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements'''

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# **Iterating Arrays**

Iterating means going through elements one by one.

AS we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

if we iterate on a 1-D array it will go through each element one by one.


In [25]:
arr = np.array([1,2,3])

for x in arr:
  print(x)

1
2
3


In [26]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [27]:
arr = np.array([[1,2,3],[4,5,6],[3,4,5]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
[3 4 5]


In [28]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [29]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [30]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
#3-d array using nditer() method
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [32]:
# Iterate through every scalar element of the 2D array skipping 1 element:

arr = np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [33]:
#sometimes we require corresponding index of the element white iterating, the ndenumerator
arr = np.array([1,2,3])
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [34]:
#initializing numpy array with same number
arr = np.full((2,2),10)
print(arr)

[[10 10]
 [10 10]]


In [36]:
#initializing numpy array within a range
arr = np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [37]:
arr = np.random.randint(1,100,5)
print(arr)

[53 45 50 52 47]


# **Joining NumPy Arrays**

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key whereas in NumPy we join arrays by axes.

we pass a sequence of arrays that we want to join to the concatenate() function, along with axis. if axis is not explicity passed, it is taken as 0.


In [39]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [40]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2), axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# **Using Stack Function**

In [42]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [43]:

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [44]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [45]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# **numpy intersection and difference**

In [46]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,8])

np.intersect1d(arr1, arr2)

array([3, 4, 5])

In [47]:
np.setdiff1d(arr1,arr2) # return unique element from arr1

array([1, 2])

In [48]:
np.setdiff1d(arr2,arr1)   # return uniq element from arr2

array([6, 8])

# **Addition of numpy array**



In [49]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,8])

a = np.sum([arr1,arr2])
print(a)

41


In [50]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,8])

a = np.sum([arr1,arr2], axis=0)

In [51]:
print(a)

[ 4  6  8 10 13]


In [52]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,8])

a= np.sum([arr1,arr2], axis=1)
print(a)

[15 26]


# **numpy array mathematics**

In [53]:
#basic Addition
arr = np.array([10,20,30])
arr = arr+1
print(arr)

[11 21 31]


In [54]:
#basic subtraction
arr = np.array([10,20,30])
arr = arr-1
print(arr)

[ 9 19 29]


In [55]:
#basic multiplication
arr = np.array([10,20,30])
arr =arr*2
print(arr)

[20 40 60]


In [56]:
#basic division
arr = np.array([10,20,30])
arr = arr/2
print(arr)

[ 5. 10. 15.]


In [57]:
arr = np.array([10,20,30])
np.mean(arr)

20.0

In [58]:
arr = np.array([10,20,30])
np.median(arr)


20.0

In [59]:
arr = np.array([10,20,30])
np.std(arr)

8.16496580927726

In [60]:
np.save('myarray', arr)

In [61]:
newarr = np.load('myarray.npy',)

In [62]:
print(newarr)

[10 20 30]


# **Splitting NumPy Arrays**

Splitting is reverse operating of joining.

joining merges multiple arrays into one and splitting breaks one array into multiple.

we use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [63]:
import numpy as np
arr = np.array([1,2,3,4,5])
new_arr = np.array_split(arr,3)
print(new_arr)
print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

[array([1, 2]), array([3, 4]), array([5])]
[1 2]
[3 4]
[5]


In [64]:
#splitting 2D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [65]:
#use the hsplit() method to split the 2-D array into array into three 2-D arrays along rows
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# **Searching Arrays**

You can search an array for a certain value, and return the indexes that grt a match

to search an array, use the where () match

In [67]:
arr = np.array([1,2,3,4,5,6,7])
x = np.where(arr==7)  # return indexes where the value is 4
print(x)

(array([6]),)


In [68]:
arr = np.array([1,2,3,4,5,6,4])
x = np.where(arr%2==0)
print(x)


(array([1, 3, 5, 6]),)


In [69]:
# find the indexes where the values are odd:
arr = np.array([1,2,3,4,5,6,4])
x = np.where(arr%2==1)
print(x)

(array([0, 2, 4]),)


In [ ]:
#