<a href="https://colab.research.google.com/github/Amarjeet-1998/Amarjeet_Portfolio/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What is NumPy?**

NumPy is a Python library used for working with arrays. it also has functions for working in domain of linear algebra, fourier transform, and the matrices. NumPy was created in 2005 by Travis Oliphant. It is an open sources project and you can use it freely. NumPy stands for Numerical Python.



# **Why Use NumPy?**

In python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional python lists. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.


# **Why is NumPy Faster than Lists?**


NumPy array are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behaviour is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. also it is optimized to work with latest CPU architectures.


# **Which Language is NumPy written in?** 

NumPy is a python library and is written partially in python, but most of the parts that require fast computation are written in C or C++.

In [1]:
'''To create an ndarray, we can pass a list, tuple or any array-like object into the array method, and it will be converted into an ndarray:'''

import numpy as np
arr = np.array([1,2,3,4,5]) #creating array
print(arr)
print(type(arr))     # check type of arr

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
print(np.__version__) # check numpy version

1.21.6


In [3]:
#use tuple to create numpy array
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [4]:
# create a 2-D array containing the values 1,2,3,4,5 and  6,7,8,9:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [5]:
#create a 1-D array containing the values 1,2,3,4,5:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
#create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3,4,5
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#Numpy Array provides the ndim attribute that returns an integer that tells us how many dimemnsions
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
#create an array with  dimensions and verify that it has 5 dimensions:
arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions: 5


In [10]:
#access array element using indexing
arr = np.array([1,2,3,4])
print(arr[1])

print(arr[2] + arr[3])  #add two element in array using indexing

2
7


In [11]:
#accessing of 2D-array element
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:', arr[0,1])
print('5th element on 2nd row:', arr[1,4])

2nd element on 1st row: 2
5th element on 2nd row: 10


In [12]:
#Access 3-D arrays 
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2]) # Access the third element of the second array of the first array:

6


In [13]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('last element from 2nd dim:', arr[1, -1])

last element from 2nd dim: 10


# **Slicing arrays**

slicing in python means taking elements from one given index to another given index.

we pass slice instead of index like this:[ start:end].

we can also define the step, like this :[start:end:step].

if we don't pass start its considered 0

if we don't pass end its considered length of array in that dimension

if we don't pass step its considered 1

In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])
print(arr[2:4])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:3])
print(arr[::2])
print(arr[-1:3])
print(arr[::-2])
print(arr[2::])
print(arr[-2:3:1])
print(arr[3:])


[2 3 4 5]
[3 4]
[5 6 7]
[1 2 3 4]
[5 6]
[2 5]
[1 3 5 7]
[]
[7 5 3 1]
[3 4 5 6 7]
[]
[4 5 6 7]


In [15]:
#slicing 2-D arrays
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0, 0:6])
print(arr[0:2 , 2])
print(arr[0:2, 1:4])


[7 8 9]
[1 2 3 4 5]
[3 8]
[[2 3 4]
 [7 8 9]]


# **Data Types in NumPy**

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsign integers etc.

below is a list of all data types in NumPy and the characters used to represent them.

i-integer b-boolean u- unsigned integer f- float c-complex float m-timedelta M-datetime O- object S-string U-unicode string V- fixed chunk of memory for other type (void)